# http://localhost:3000/user/${userId}
# http://localhost:3000/user/${userId}/activity
# http://localhost:3000/user/${userId}/average-sessions
# http://localhost:3000/user/${userId}/performance

# example

# http://localhost:3000/user/12/performance
# http://localhost:3000/user/18

http://localhost:3000/user/12